/*******************************************************************************
 * (c) Copyright 2020 Micro Focus or one of its affiliates
 *
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the 
 * "Software"), to deal in the Software without restriction, including without 
 * limitation the rights to use, copy, modify, merge, publish, distribute, 
 * sublicense, and/or sell copies of the Software, and to permit persons to 
 * whom the Software is furnished to do so, subject to the following 
 * conditions:
 * 
 * The above copyright notice and this permission notice shall be included 
 * in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY 
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE 
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
 * PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 ******************************************************************************/
package com.fortify.impexp.common.processor.retriever;

import java.util.Collection;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.springframework.beans.factory.ObjectFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.OrderComparator;
import org.springframework.stereotype.Component;

import com.fortify.impexp.common.processor.IProcessor;
import com.fortify.impexp.common.processor.IProcessorFactory;
import com.fortify.impexp.common.processor.entity.IEntityDescriptor;

/**
 * This class allows for retrieving the list of active {@link IProcessor}
 * instances for a given {@link IEntityDescriptor}. An instance of this 
 * class is available as a singleton bean through the {@link Component} 
 * annotation. The actual {@link IProcessorFactory} instances are retrieved 
 * using an {@link ObjectFactory} though, in order to allow for properly 
 * scoped factories. The collection returned by 
 * {@link #getActiveProcessors(IEntityDescriptor)} is sorted based on
 * {@link IProcessorFactory#getOrder()}, allowing for {@link IProcessor}
 * instances generated by an {@link IProcessorFactory} with lower order
 * to execute before instances generated by an {@link IProcessorFactory}
 * with higher order.
 * 
 * @author Ruud Senden
 *
 */
@Component
public class ActiveProcessorsRetriever {
	@Autowired private ObjectFactory<Collection<IProcessorFactory<?>>> allProcessorFactoriesFactory;
	
	public final Collection<IProcessor<?>> getActiveProcessors(final IEntityDescriptor entityDescriptor) {
		return getActiveProcessorsStream(entityDescriptor)
				.map(factory->(IProcessor<?>)factory.getProcessor())
				.collect(Collectors.toList());
	}

	private Stream<IProcessorFactory<?>> getActiveProcessorsStream(final IEntityDescriptor entityDescriptor) {
		return allProcessorFactoriesFactory
				.getObject()
				.stream()
				.filter(factory->factory.isActive(entityDescriptor))
				.sorted(new OrderComparator());
	}
}
