logging:
  level:
    org.springframework.beans.factory: WARN
    com.fortify.impexp: TRACE

spring:
  profiles:
    active: default
  main:
    web-application-type: NONE

from.ssc:
  baseUrl: http://localhost:1920/ssc
  userName: ssc
  password: Fortify123!
  load:
    releases:
      include:
        fields: id
        subEntities: filterSets
      filter:
        maxResults: 3
      orderBy:
        field: id
      
      
    vulnerabilities:
      include: 
        fields: id                                     # Generic - loader
        subEntities: details, comments                 # Generic - loader
        status: hidden, removed, suppressed            # Specific - SSC vuln loader
      transform:
        add[details.idDescription]: Identifier ${id}   # Generic - entity processing
      filter:
#        maxResults: -1                                 # Generic - loader
        filterSet: Quick View                          # Specific - SSC vuln loader
        matchFieldRegex[details.issueName]: Cross.*    # Generic - entity processing
      orderBy:                                         # Generic - SSC
        field: id
      exportStatus:                                    # Specific - different impl for each entity source and type
        jira: #Map<String, ExportStatus>
          storeAsBugLink: true                         # SSC or FoD
          #storeAsComment: Vulnerability submitted to {} # FoD, maybe SSC?
          storeAsCustomTag: JiraBugURL
          customTag[Extra]: Extra ${deepLink}
          primaryCustomTag: Jira Bug Link
    
from.mock:
  enabled: true

to.mock:
  entity:
    sources: mock, ssc
    types: release, vulnerability, mock_custom
    
to.file:
  - sources: mock, ssc
    types: release, vulnerability
    fileName: expression
    format: json/csv/plain
    formatOptions: xx, yy    
    
to.jira:
  baseUrl: http://localhost:8989/jira
  userName:
  password:
  vulnerabilities: #Map<String, JiraVulnExporterConfig>
    ssc:
      transform: # Generic for any source
        add[isOpen]: not suppressed, not hidden, not removed, ...
#      exportNew: # Generic for any source
#        filter: isOpen, critical|high
#        groupBy: expression # Only for new vulns; existing vulns are grouped by bug link
#      updateExisting: # Generic for any source
#        filter: xxx
#      fields:
#        field[abc]: expression
#        field[def]: expression
#        appendToField[abc]: expression
#        updateDuringStateManagent: abc, def, ghi.xyz
#      state: open/close transitions
        