logging:
  level:
    org.springframework.beans.factory: WARN
    com.fortify.impexp.common.api.processor.AbstractEnabledProcessorsLoader: TRACE

spring:
  profiles:
    active: default
  main:
    web-application-type: NONE

from.ssc:
  baseUrl: http://localhost:1920/ssc
  userName: ssc
  password: Fortify123!
  load:
    releases:
      fields: id
      includeSubEntities: filterSets
      orderBy:
        field: id
      maxResults: 5
    vulnerabilities:
      include: all
      fields: id
      filterSet: Quick View
      includeSubEntities: details, comments
    
    
    
  
from.mock:
  enabled: true

to.mock:
  entity:
    sources: mock, ssc
    types: release, vulnerability, mock_custom