logging:
  level:
    org.springframework.beans.factory: WARN
    com.fortify.impexp.common.api.processor.AbstractEnabledProcessorsLoader: TRACE

spring:
  profiles:
    active: default
  main:
    web-application-type: NONE

from.ssc:
#  enabled: true # TODO Implement this for root processors
  
from.mock:
#  enabled: true

to.mock:
  simple: test
  source:
    systems: mock, ssc
    entities: vulnerability, mock_custom
  

ssc.conn:
  baseUrl: http://localhost:1920/ssc
  userName: ssc
  password: Fortify123!